### ISSUE TITLE
clid crashes at start

### ISSUE THREAD

**Issue by Hund** [GokulSoumya/clid#1]
I'm running Funtoo and just installed it via pip.

```
$ clid
Traceback (most recent call last):
  File "/home/johan/.local/bin/clid", line 11, in <module>
    sys.exit(run())
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/__main__.py", line 8, in run
    main.ClidApp().run()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplicationManaged.py", line 148, in main
    self.onStart()
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/main.py", line 158, in onStart
    self.addForm("MAIN", ClidInterface)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplicationManaged.py", line 55, in addForm
    fm = FormClass( parentApp=self, *args, **keywords)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/fmFormMuttActive.py", line 215, in __init__
    super(FormMuttActiveTraditional, self).__init__(*args, **keywords)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/fmFormMutt.py", line 27, in __init__
    super(FormMutt, self).__init__(cycle_widgets=cycle_widgets, *args, **keywords)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/fmForm.py", line 70, in __init__
    self.create()
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/main.py", line 133, in create
    self.set_value(self.DATA_CONTROLER())   # isn't automatically done(open issue ?)
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/database.py", line 27, in __init__
    self.load_files_and_set_values()   # set `file_dict` and `_values` attribute
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/database.py", line 39, in load_files_and_set_values
    base = configobj.ConfigObj(CONFIG)['music_dir']
  File "/usr/lib64/python3.4/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'music_dir'
```

My `~/Music` is a symlink, if that has something to do with it.

**Comment by sudormrfbin** [comment]
It's fixed now, I think, in v0.6.1. Let me know if it still crashes.
I hope you like my app :)

P.S: It didn't crash because `~/Music` was a symlink.

**Comment by Hund** [comment]
I can start it now. :) But, it crashes after a few seconds if I scroll down the list.

```
$ clid
Traceback (most recent call last):
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/database.py", line 83, in parse_meta_for_status
    meta = stagger.read_tag(self.file_dict[filename])
  File "/home/johan/.local/lib64/python3.4/site-packages/stagger/tags.py", line 81, in read_tag
    (cls, offset, length) = detect_tag(file)
  File "/home/johan/.local/lib64/python3.4/site-packages/stagger/tags.py", line 108, in detect_tag
    raise NoTagError("ID3v2 tag not found")
stagger.errors.NoTagError: ID3v2 tag not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johan/.local/bin/clid", line 11, in <module>
    load_entry_point('clid==0.6.1', 'console_scripts', 'clid')()
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/__main__.py", line 8, in run
    main.ClidApp().run()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/wgtextbox.py", line 383, in edit
    self.get_and_use_key_press()
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/wgwidget.py", line 610, in get_and_use_key_press
    self.handle_input(ch)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/fmFormMuttActive.py", line 180, in handle_input
    rtn = self.linked_widget.handle_input(inputch)
  File "/home/johan/.local/lib64/python3.4/site-packages/npyscreen/wgwidget.py", line 71, in handle_input
    self.handlers[_input](_input)
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/main.py", line 99, in h_cursor_line_down
    self.set_status(filename)
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/main.py", line 85, in set_status
    self.parent.wStatus2.value = self.parent.value.parse_meta_for_status(filename=filename)
  File "/home/johan/.local/lib64/python3.4/site-packages/clid/database.py", line 90, in parse_meta_for_status
    self.meta_cache[filename] = _const.FORMAT_PAT.sub('', self.specifiers)
TypeError: expected string or buffer
```

It seems like a good application though. :) But I do have a few sugestions, as a Vim-user with regular users in mind. When you're viewing a track, it would be nice if you could navigate using both `j` and `k` and not just the arrow keys. To edit a field, you should have to enter a input mode using either `i` or the Enter-key. And to exit input mode you should have to use either `Esc` or the Enter-key. And then to go back to the list you should be able to use `Esc`.

**Comment by sudormrfbin** [comment]
It's fixed now(v0.6.3). Thanks, by the way :) It really does feel good to see someone else using you app ;) And I'll add the Vim key-bindings to my TODO list.

**Comment by Hund** [comment]
Thanks! :)

I bet it does! It's a neat piece of software. :)

**Comment by sudormrfbin** [comment]
I've updated the app and added some Vim keybindings ;) Just the basics(movement keys, `x`, `X`, `a` and `A`). BTW, the `Esc` key is a bit slow to respond.

**Comment by Hund** [comment]
Cool! I'll check it out. :)
